module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/FZCfxAjwGDp2klCqLz3Lci',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/cmtnzr.png',
    NEWSLETTER_JID: '120363418252392851@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ASTRIX-MD',
    OWNER_NAME: 'ASTRIX-SIR',
    OWNER_NUMBER: '263715831216',
    BOT_VERSION: ',1.0.0',
    BOT_FOOTER: '> ASTRIX-MD-MINI-BOT',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb0Tq5eKbYMSSePQtI34',
};
